"use client";

import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { useState } from "react";

const jakarta = Plus_Jakarta_Sans({
  subsets: ["latin"], // required
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-jakarta",
  display: "swap",
});

 const metadata: Metadata = {
  title: "portfolio-owais",
  description: "Generated by create next app",
  icons:{
    icon:"/icon.jpg"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const [state, setState] = useState<boolean>(false)
  

  return (
    <html lang="en">
     
      <body className={`bg-base ${jakarta.variable}  antialiased ${state ? "overflow-hidden" : "overflow-y-scroll"} `}>
        <Navbar  isOpen={state} setIsOpen={setState} />
        {children}
      </body>
    </html>
  );
}
